import React from 'react';
import { ShieldAlert, X, AlertTriangle, CheckCircle2 } from 'lucide-react';

interface DisclaimerModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const DisclaimerModal: React.FC<DisclaimerModalProps> = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-fade-in">
      <div className="relative w-full max-w-2xl bg-[#0c1222] border border-cyan-500/30 rounded-xl shadow-2xl p-6 overflow-hidden">
        {/* Decorative corner glow */}
        <div className="absolute top-0 right-0 w-32 h-32 bg-cyan-500/10 rounded-full blur-2xl pointer-events-none" />
        
        <div className="flex items-start justify-between border-b border-slate-800 pb-4">
          <div className="flex items-center gap-3">
            <div className="p-2.5 rounded-lg bg-cyan-500/10 border border-cyan-500/30 text-cyan-400">
              <ShieldAlert className="w-6 h-6" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-slate-100 flex items-center gap-2">
                DEMO ENVIRONMENT DISCLOSURE
                <span className="text-xs font-mono font-normal px-2 py-0.5 rounded bg-cyan-500/20 text-cyan-300 border border-cyan-500/30">
                  SIH26183
                </span>
              </h2>
              <p className="text-xs text-slate-400">
                Indian Cyber Crime Coordination Centre (I4C) — Defensive Analytics Prototype
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded-lg text-slate-400 hover:text-slate-100 hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="mt-4 space-y-3.5 text-xs text-slate-300 leading-relaxed">
          <div className="p-3 rounded-lg bg-amber-500/10 border border-amber-500/20 flex items-start gap-2.5">
            <AlertTriangle className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
            <p>
              <strong className="text-amber-200">Synthetic Demonstration Data:</strong> All cryptocurrency addresses, transaction hashes, block records, and VASP clusters shown in this prototype are synthetic, designed strictly for the Smart India Hackathon evaluation demonstration.
            </p>
          </div>

          <div className="space-y-2">
            <div className="flex items-start gap-2">
              <CheckCircle2 className="w-3.5 h-3.5 text-cyan-400 shrink-0 mt-0.5" />
              <p>
                <strong>Risk Score Heuristics:</strong> Risk scores and Fraud DNA indicators are analytical signals generated by heuristic algorithms and do not independently establish ownership, criminal intent, or guilt.
              </p>
            </div>

            <div className="flex items-start gap-2">
              <CheckCircle2 className="w-3.5 h-3.5 text-cyan-400 shrink-0 mt-0.5" />
              <p>
                <strong>VASP Attribution:</strong> VASP attributions represent investigative leads derived from observable cluster topological relationships, not judicial proof of account holder identity.
              </p>
            </div>

            <div className="flex items-start gap-2">
              <CheckCircle2 className="w-3.5 h-3.5 text-cyan-400 shrink-0 mt-0.5" />
              <p>
                <strong>Defensive Architecture:</strong> This platform is strictly read-only and analytical. It does not execute wallet transfers, access private keys, or bypass cryptographic protections.
              </p>
            </div>

            <div className="flex items-start gap-2">
              <CheckCircle2 className="w-3.5 h-3.5 text-cyan-400 shrink-0 mt-0.5" />
              <p>
                <strong>Government Integration Adapters:</strong> NCRP and SAHYOG modules use prototype integration adapter contracts to illustrate interoperability.
              </p>
            </div>
          </div>
        </div>

        <div className="mt-6 pt-4 border-t border-slate-800/80 flex items-center justify-between">
          <span className="text-[11px] font-mono text-slate-400">
            FRAUDTRACE-X v2.6.4-SEC // SIH-MHA-I4C
          </span>
          <button
            onClick={onClose}
            className="px-4 py-2 text-xs font-semibold rounded-lg bg-cyan-500 hover:bg-cyan-400 text-slate-950 transition-colors shadow-lg shadow-cyan-500/20"
          >
            Acknowledge & Proceed
          </button>
        </div>
      </div>
    </div>
  );
};
